### PR TITLE
floatingdockfixworkaround

### PR DESCRIPTION
**Pull request by b4db1r3**
Added support with a workaround to FloatingDock

### CODE REVIEW

**Comment by bb91z** [comment]
id like to help with this tweak. I've started also but you made more progress than me, so.. i will keep in track with your changes and add my own code to fix things also, lets collaborate

**Comment by Lizynz** [comment]
> id like to help with this tweak. I've started also but you made more progress than me, so.. i will keep in track with your changes and add my own code to fix things also, lets collaborate

Thanks, I've added your corrections. Any contribution is welcome.

**Comment by bb91z** [comment]
Thanks, I'm trying to fix the upside down bug when you open a folder after unlocking the device.

**Comment by bb91z** [comment]
I've found a partial fix for the upside down folder bug, but need to work on it

With the fix the folder is overlapping the icons below, so maybe you'll have an idea to continue the fix 

I'll upload it later today

**Comment by Lizynz** [comment]
> I've found a partial fix for the upside down folder bug, but need to work on it
> 
> With the fix the folder is overlapping the icons below, so maybe you'll have an idea to continue the fix
> 
> I'll upload it later today


I didn’t even understand what were talking about until I accidentally saw an open folder at the top when I tried to go into it with the tweak installed FloatingDockXVI.

**Comment by bb91z** [comment]
Yeah, seems like there's no easy fix. Everything I did introduced another problem

**Comment by bb91z** [comment]
So it's something with floatingdock, as I don't use regular dock I didn't tested it with it

**Comment by Lizynz** [comment]
> So it's something with floatingdock, as I don't use regular dock I didn't tested it with it

I also not use a floating dock, users with ipad will have certain difficulties, they will have to wait until solution falls from heaven 😁

**Pull request merged**
